// ============================================================
// METABOLIC HARMONY — Pathway Ratio Assignments
// ============================================================
// Generated from harmonic_map.json
// Total pathways: 170
//
// Prime Architecture:
//   2, 3    → Energy (glycolysis, TCA, fermentation)
//   5       → Information (nucleotides, polyamines)
//   7       → Structural identity (amino acids, membranes)
//   11      → Catalytic (NAD, CoA, B12, thiamin)
//   13      → Aromatic gate (chorismate, siderophores)
//
// Composites:
//   27 = 3³      → Deep TCA / nitrogen
//   35 = 5×7    → Biosynthetic structure
//   49 = 7²     → Dense structural
//   55 = 5×11   → Biosynthetic × cofactor
//   77 = 7×11   → Structural × cofactor
//   91 = 7×13   → Structural × aromatic
//   143 = 11×13 → Cofactor × aromatic
//   231 = 3×7×11 → TCA × structural × cofactor
//   245 = 7²×5  → Cell envelope
// ============================================================

const COMPOSED_RATIOS = [
  {
    id: 'PWY-6590',
    name: "superpathway of Clostridium acetobutylicum acidogenic fermentation",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 9,
    d: 8,
    ratio: '9/8',
    value: 1.125,
    consonance: 72,
    prime_limit: 3,
    polarity: 0.922,
    polarity_label: 'harmonic',
    cents: 203.91,
    derivation: "/9 family - Clostridium complex fermentation"
  },
  {
    id: 'PWY-6883',
    name: "pyruvate fermentation to butanol II",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 32,
    d: 27,
    ratio: '32/27',
    value: 1.185185,
    consonance: 864,
    prime_limit: 3,
    polarity: -0.891,
    polarity_label: 'subharmonic',
    cents: 294.13,
    derivation: "Pythagorean comma zone - rare butanol"
  },
  {
    id: 'PWY-5100',
    name: "pyruvate fermentation to acetate and lactate II",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 4,
    d: 3,
    ratio: '4/3',
    value: 1.333333,
    consonance: 12,
    prime_limit: 3,
    polarity: -0.828,
    polarity_label: 'subharmonic',
    cents: 498.04,
    derivation: "/3 family - acetate+lactate feeds cross-feeders"
  },
  {
    id: 'CENTFERM-PWY',
    name: "pyruvate fermentation to butanoate",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 3,
    d: 2,
    ratio: '3/2',
    value: 1.5,
    consonance: 6,
    prime_limit: 3,
    polarity: 0.774,
    polarity_label: 'harmonic',
    cents: 701.96,
    derivation: "butyrate canonical - THE healthy gut interval (3/2)"
  },
  {
    id: 'PROPFERM-PWY',
    name: "L-alanine fermentation to propanoate and acetate",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 27,
    d: 16,
    ratio: '27/16',
    value: 1.6875,
    consonance: 432,
    prime_limit: 3,
    polarity: 0.726,
    polarity_label: 'harmonic',
    cents: 905.87,
    derivation: "27/ family - alanine to propionate"
  },
  {
    id: 'PWY-6588',
    name: "pyruvate fermentation to acetone",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 16,
    d: 9,
    ratio: '16/9',
    value: 1.777778,
    consonance: 144,
    prime_limit: 3,
    polarity: -0.707,
    polarity_label: 'subharmonic',
    cents: 996.09,
    derivation: "/9 family - acetone (solvent)"
  },
  {
    id: 'ANAEROFRUCAT-PWY',
    name: "homolactic fermentation",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 8,
    d: 3,
    ratio: '8/3',
    value: 2.666667,
    consonance: 24,
    prime_limit: 3,
    polarity: -0.586,
    polarity_label: 'subharmonic',
    cents: 1698.04,
    derivation: "/3 family - pure lactate production"
  },
  {
    id: 'PWY-5677',
    name: "succinate fermentation to butanoate",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 27,
    d: 8,
    ratio: '27/8',
    value: 3.375,
    consonance: 216,
    prime_limit: 3,
    polarity: 0.533,
    polarity_label: 'harmonic',
    cents: 2105.87,
    derivation: "27/ family - succinate to butyrate"
  },
  {
    id: 'P122-PWY',
    name: "heterolactic fermentation",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 32,
    d: 9,
    ratio: '32/9',
    value: 3.555556,
    consonance: 288,
    prime_limit: 3,
    polarity: -0.522,
    polarity_label: 'subharmonic',
    cents: 2196.09,
    derivation: "/9 family - heterolactic"
  },
  {
    id: 'PWY-5676',
    name: "acetyl-CoA fermentation to butanoate II",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 16,
    d: 3,
    ratio: '16/3',
    value: 5.333333,
    consonance: 48,
    prime_limit: 3,
    polarity: -0.453,
    polarity_label: 'subharmonic',
    cents: 2898.04,
    derivation: "/3 family - cross-feeding route to butyrate"
  },
  {
    id: 'P108-PWY',
    name: "pyruvate fermentation to propanoate I",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 27,
    d: 4,
    ratio: '27/4',
    value: 6.75,
    consonance: 108,
    prime_limit: 3,
    polarity: 0.421,
    polarity_label: 'harmonic',
    cents: 3305.87,
    derivation: "27/ family - propionate canonical"
  },
  {
    id: 'P163-PWY',
    name: "L-lysine fermentation to acetate and butanoate",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 64,
    d: 9,
    ratio: '64/9',
    value: 7.111111,
    consonance: 576,
    prime_limit: 3,
    polarity: -0.414,
    polarity_label: 'subharmonic',
    cents: 3396.09,
    derivation: "/9 family - lysine to butyrate"
  },
  {
    id: 'P461-PWY',
    name: "hexitol fermentation to lactate, formate, ethanol and acetate",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 32,
    d: 3,
    ratio: '32/3',
    value: 10.666667,
    consonance: 96,
    prime_limit: 3,
    polarity: -0.369,
    polarity_label: 'subharmonic',
    cents: 4098.04,
    derivation: "/3 family - hexitol substrate"
  },
  {
    id: 'FERMENTATION-PWY',
    name: "mixed acid fermentation",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 27,
    d: 2,
    ratio: '27/2',
    value: 13.5,
    consonance: 54,
    prime_limit: 3,
    polarity: 0.348,
    polarity_label: 'harmonic',
    cents: 4505.87,
    derivation: "27/ family - mixed acid (high consonance for importance)"
  },
  {
    id: 'PWY-6863',
    name: "pyruvate fermentation to hexanol",
    category: 'energy',
    subcategory: 'Fermentation',
    n: 128,
    d: 9,
    ratio: '128/9',
    value: 14.222222,
    consonance: 1152,
    prime_limit: 3,
    polarity: -0.343,
    polarity_label: 'subharmonic',
    cents: 4596.09,
    derivation: "/9 family - rare hexanol (has MS data)"
  },
  {
    id: 'PWY-1042',
    name: "glycolysis IV (plant cytosol)",
    category: 'energy',
    subcategory: 'Glycolysis/Gluconeogenesis',
    n: 1,
    d: 1,
    ratio: '1/1',
    value: 1.0,
    consonance: 1,
    prime_limit: 1,
    polarity: 0.0,
    polarity_label: 'neutral',
    cents: 0.0,
    derivation: "exponential 2-limit growth (1→2→4→16)"
  },
  {
    id: 'GLUCONEO-PWY',
    name: "gluconeogenesis I",
    category: 'energy',
    subcategory: 'Glycolysis/Gluconeogenesis',
    n: 2,
    d: 1,
    ratio: '2/1',
    value: 2.0,
    consonance: 2,
    prime_limit: 2,
    polarity: 0.667,
    polarity_label: 'harmonic',
    cents: 1200.0,
    derivation: "exponential 2-limit growth (1→2→4→16)"
  },
  {
    id: 'GLYCOLYSIS-E-D',
    name: "superpathway of glycolysis and Entner-Doudoroff",
    category: 'energy',
    subcategory: 'Glycolysis/Gluconeogenesis',
    n: 4,
    d: 1,
    ratio: '4/1',
    value: 4.0,
    consonance: 4,
    prime_limit: 2,
    polarity: 0.5,
    polarity_label: 'harmonic',
    cents: 2400.0,
    derivation: "exponential 2-limit growth (1→2→4→16)"
  },
  {
    id: 'PWY-7446',
    name: "sulfoglycolysis",
    category: 'energy',
    subcategory: 'Glycolysis/Gluconeogenesis',
    n: 16,
    d: 1,
    ratio: '16/1',
    value: 16.0,
    consonance: 16,
    prime_limit: 2,
    polarity: 0.333,
    polarity_label: 'harmonic',
    cents: 4800.0,
    derivation: "exponential 2-limit growth (1→2→4→16)"
  },
  {
    id: 'GLYOXYLATE-BYPASS',
    name: "glyoxylate cycle",
    category: 'energy',
    subcategory: 'Glyoxylate Cycle',
    n: 8,
    d: 1,
    ratio: '8/1',
    value: 8.0,
    consonance: 8,
    prime_limit: 2,
    polarity: 0.4,
    polarity_label: 'harmonic',
    cents: 3600.0,
    derivation: "glycolysis-derived stress harmonic (8/1 → 81/8)"
  },
  {
    id: 'PWY-5705',
    name: "allantoin degradation to glyoxylate III",
    category: 'energy',
    subcategory: 'Glyoxylate Cycle',
    n: 81,
    d: 8,
    ratio: '81/8',
    value: 10.125,
    consonance: 648,
    prime_limit: 3,
    polarity: 0.375,
    polarity_label: 'harmonic',
    cents: 4007.82,
    derivation: "glycolysis-derived stress harmonic (8/1 → 81/8)"
  },
  {
    id: 'PWY-2221',
    name: "Entner-Doudoroff pathway III (semi-phosphorylative)",
    category: 'energy',
    subcategory: 'Pentose Phosphate',
    n: 9,
    d: 4,
    ratio: '9/4',
    value: 2.25,
    consonance: 36,
    prime_limit: 3,
    polarity: 0.631,
    polarity_label: 'harmonic',
    cents: 1403.91,
    derivation: "prime-5 biosynthetic primer (5/1 → 5/2 → 5/3)"
  },
  {
    id: 'PENTOSE-P-PWY',
    name: "pentose phosphate pathway",
    category: 'energy',
    subcategory: 'Pentose Phosphate',
    n: 9,
    d: 2,
    ratio: '9/2',
    value: 4.5,
    consonance: 18,
    prime_limit: 3,
    polarity: 0.48,
    polarity_label: 'harmonic',
    cents: 2603.91,
    derivation: "prime-5 biosynthetic primer (5/1 → 5/2 → 5/3)"
  },
  {
    id: 'NONOXIPENT-PWY',
    name: "pentose phosphate pathway (non-oxidative branch)",
    category: 'energy',
    subcategory: 'Pentose Phosphate',
    n: 9,
    d: 1,
    ratio: '9/1',
    value: 9.0,
    consonance: 9,
    prime_limit: 3,
    polarity: 0.387,
    polarity_label: 'harmonic',
    cents: 3803.91,
    derivation: "prime-5 biosynthetic primer (5/1 → 5/2 → 5/3)"
  },
  {
    id: 'PWY-3781',
    name: "aerobic respiration I (cytochrome c)",
    category: 'energy',
    subcategory: 'Respiration',
    n: 12,
    d: 1,
    ratio: '12/1',
    value: 12.0,
    consonance: 12,
    prime_limit: 3,
    polarity: 0.358,
    polarity_label: 'harmonic',
    cents: 4301.96,
    derivation: "3-limit amplification (12/1)"
  },
  {
    id: 'TCA',
    name: "TCA cycle I (prokaryotic)",
    category: 'energy',
    subcategory: 'TCA Cycle',
    n: 3,
    d: 1,
    ratio: '3/1',
    value: 3.0,
    consonance: 3,
    prime_limit: 3,
    polarity: 0.558,
    polarity_label: 'harmonic',
    cents: 1901.96,
    derivation: "prime-3 introduction (3/1 → 3/2)"
  },
  {
    id: 'TCA-GLYOX-BYPASS',
    name: "superpathway of glyoxylate bypass and TCA",
    category: 'energy',
    subcategory: 'TCA Cycle',
    n: 6,
    d: 1,
    ratio: '6/1',
    value: 6.0,
    consonance: 6,
    prime_limit: 3,
    polarity: 0.436,
    polarity_label: 'harmonic',
    cents: 3101.96,
    derivation: "prime-3 introduction (3/1 → 3/2)"
  },
  {
    id: 'TRPSYN-PWY',
    name: "L-tryptophan biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 20,
    ratio: '21/20',
    value: 1.05,
    consonance: 420,
    prime_limit: 7,
    polarity: 0.594,
    polarity_label: 'harmonic',
    cents: 84.47,
    derivation: "tryptophan — deep, high-cost aromatic identity"
  },
  {
    id: 'PWY-2942',
    name: "L-lysine biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 6,
    ratio: '7/6',
    value: 1.166667,
    consonance: 42,
    prime_limit: 7,
    polarity: 0.36,
    polarity_label: 'harmonic',
    cents: 266.87,
    derivation: "lysine — buffered / moderated binding"
  },
  {
    id: 'PWY-5505',
    name: "L-glutamate and L-glutamine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 9,
    d: 7,
    ratio: '9/7',
    value: 1.285714,
    consonance: 63,
    prime_limit: 7,
    polarity: 0.106,
    polarity_label: 'neutral',
    cents: 435.08,
    derivation: "glutamate/glutamine — nitrogen currency"
  },
  {
    id: 'PWY-5154',
    name: "L-arginine biosynthesis III (via N-acetyl-L-citrulline)",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 16,
    ratio: '21/16',
    value: 1.3125,
    consonance: 336,
    prime_limit: 7,
    polarity: 0.836,
    polarity_label: 'harmonic',
    cents: 470.78,
    derivation: "arginine — contextual / conditional signaling"
  },
  {
    id: 'PWY-6628',
    name: "superpathway of L-phenylalanine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 5,
    ratio: '7/5',
    value: 1.4,
    consonance: 35,
    prime_limit: 7,
    polarity: 0.134,
    polarity_label: 'neutral',
    cents: 582.51,
    derivation: "phenylalanine — base aromatic identity"
  },
  {
    id: 'HISTSYN-PWY',
    name: "L-histidine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 5,
    d: 3,
    ratio: '5/3',
    value: 1.666667,
    consonance: 15,
    prime_limit: 5,
    polarity: 0.183,
    polarity_label: 'neutral',
    cents: 884.36,
    derivation: "histidine — catalytic hinge embedded in metabolic flow"
  },
  {
    id: 'ILEUSYN-PWY',
    name: "L-isoleucine biosynthesis I (from threonine)",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 4,
    ratio: '7/4',
    value: 1.75,
    consonance: 28,
    prime_limit: 7,
    polarity: 0.712,
    polarity_label: 'harmonic',
    cents: 968.83,
    derivation: "differentiated BCAA structure"
  },
  {
    id: 'PWY-6630',
    name: "superpathway of L-tyrosine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 10,
    ratio: '21/10',
    value: 2.1,
    consonance: 210,
    prime_limit: 7,
    polarity: 0.401,
    polarity_label: 'harmonic',
    cents: 1284.47,
    derivation: "tyrosine — functionalized aromatic identity"
  },
  {
    id: 'PWY-4981',
    name: "L-proline biosynthesis II (from arginine)",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 15,
    d: 7,
    ratio: '15/7',
    value: 2.142857,
    consonance: 105,
    prime_limit: 7,
    polarity: 0.235,
    polarity_label: 'neutral',
    cents: 1319.44,
    derivation: "proline — structural curvature"
  },
  {
    id: 'PWY-5097',
    name: "L-lysine biosynthesis VI",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 3,
    ratio: '7/3',
    value: 2.333333,
    consonance: 21,
    prime_limit: 7,
    polarity: 0.248,
    polarity_label: 'neutral',
    cents: 1466.87,
    derivation: "lysine — identity engaged in interaction"
  },
  {
    id: 'ASPASN-PWY',
    name: "superpathway of L-aspartate and L-asparagine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 18,
    d: 7,
    ratio: '18/7',
    value: 2.571429,
    consonance: 126,
    prime_limit: 7,
    polarity: 0.074,
    polarity_label: 'neutral',
    cents: 1635.08,
    derivation: "aspartate/asparagine — TCA currency"
  },
  {
    id: 'PWY-5103',
    name: "L-isoleucine biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 8,
    ratio: '21/8',
    value: 2.625,
    consonance: 168,
    prime_limit: 7,
    polarity: 0.59,
    polarity_label: 'harmonic',
    cents: 1670.78,
    derivation: "leucine variant — structure engaged with circulation"
  },
  {
    id: 'THRESYN-PWY',
    name: "superpathway of L-threonine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 10,
    d: 3,
    ratio: '10/3',
    value: 3.333333,
    consonance: 30,
    prime_limit: 5,
    polarity: 0.134,
    polarity_label: 'neutral',
    cents: 2084.36,
    derivation: "threonine — branch point"
  },
  {
    id: 'VALSYN-PWY',
    name: "L-valine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 2,
    ratio: '7/2',
    value: 3.5,
    consonance: 14,
    prime_limit: 7,
    polarity: 0.525,
    polarity_label: 'harmonic',
    cents: 2168.83,
    derivation: "simplest structural BCAA"
  },
  {
    id: 'MET-SAM-PWY',
    name: "superpathway of S-adenosyl-L-methionine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 35,
    d: 9,
    ratio: '35/9',
    value: 3.888889,
    consonance: 315,
    prime_limit: 7,
    polarity: 0.298,
    polarity_label: 'harmonic',
    cents: 2351.23,
    derivation: "SAM — methylation currency (35 = 7×5)"
  },
  {
    id: 'PWY-5104',
    name: "L-isoleucine biosynthesis IV",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 63,
    d: 16,
    ratio: '63/16',
    value: 3.9375,
    consonance: 1008,
    prime_limit: 7,
    polarity: 0.503,
    polarity_label: 'harmonic',
    cents: 2372.74,
    derivation: "leucine variant — high metabolic turnover"
  },
  {
    id: 'DAPLYSINESYN-PWY',
    name: "L-lysine biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 14,
    d: 3,
    ratio: '14/3',
    value: 4.666667,
    consonance: 42,
    prime_limit: 7,
    polarity: 0.189,
    polarity_label: 'neutral',
    cents: 2666.87,
    derivation: "lysine — amplified structural anchoring"
  },
  {
    id: 'ARGSYNBSUB-PWY',
    name: "L-arginine biosynthesis II (acetyl cycle)",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 4,
    ratio: '21/4',
    value: 5.25,
    consonance: 84,
    prime_limit: 7,
    polarity: 0.455,
    polarity_label: 'harmonic',
    cents: 2870.78,
    derivation: "arginine — moderated nitrogen routing"
  },
  {
    id: 'HSERMETANA-PWY',
    name: "L-methionine biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 35,
    d: 6,
    ratio: '35/6',
    value: 5.833333,
    consonance: 210,
    prime_limit: 7,
    polarity: 0.371,
    polarity_label: 'harmonic',
    cents: 3053.18,
    derivation: "methionine III — transsulfuration (35 = 7×5)"
  },
  {
    id: 'PWY-5101',
    name: "L-isoleucine biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 189,
    d: 32,
    ratio: '189/32',
    value: 5.90625,
    consonance: 6048,
    prime_limit: 7,
    polarity: 0.438,
    polarity_label: 'harmonic',
    cents: 3074.69,
    derivation: "leucine variant — specialized / condition-dependent"
  },
  {
    id: 'SULFATE-CYS-PWY',
    name: "superpathway of sulfate assimilation and cysteine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 45,
    d: 7,
    ratio: '45/7',
    value: 6.428571,
    consonance: 315,
    prime_limit: 7,
    polarity: 0.312,
    polarity_label: 'harmonic',
    cents: 3221.4,
    derivation: "cysteine — embodied redox identity (disulfides, glutathione, Fe–S)"
  },
  {
    id: 'BRANCHED-CHAIN-AA-SYN-PWY',
    name: "superpathway of branched amino acid biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 7,
    d: 1,
    ratio: '7/1',
    value: 7.0,
    consonance: 7,
    prime_limit: 7,
    polarity: 0.416,
    polarity_label: 'harmonic',
    cents: 3368.83,
    derivation: "prime-7 introduction — protein identity / hydrophobic core"
  },
  {
    id: 'SER-GLYSYN-PWY',
    name: "superpathway of L-serine and glycine biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 25,
    d: 3,
    ratio: '25/3',
    value: 8.333333,
    consonance: 75,
    prime_limit: 5,
    polarity: 0.311,
    polarity_label: 'harmonic',
    cents: 3670.67,
    derivation: "serine/glycine — one-carbon supply"
  },
  {
    id: 'PWY-2941',
    name: "L-lysine biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 28,
    d: 3,
    ratio: '28/3',
    value: 9.333333,
    consonance: 84,
    prime_limit: 7,
    polarity: 0.153,
    polarity_label: 'neutral',
    cents: 3866.87,
    derivation: "lysine — high-affinity interaction"
  },
  {
    id: 'PWY-6936',
    name: "seleno-amino acid biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 135,
    d: 14,
    ratio: '135/14',
    value: 9.642857,
    consonance: 1890,
    prime_limit: 7,
    polarity: 0.342,
    polarity_label: 'harmonic',
    cents: 3923.35,
    derivation: "seleno-amino acids — rare, constrained high-kinetic redox identity"
  },
  {
    id: 'ARGSYN-PWY',
    name: "L-arginine biosynthesis I (via L-ornithine)",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 21,
    d: 2,
    ratio: '21/2',
    value: 10.5,
    consonance: 42,
    prime_limit: 7,
    polarity: 0.371,
    polarity_label: 'harmonic',
    cents: 4070.78,
    derivation: "arginine — primary directional signaling"
  },
  {
    id: 'HOMOSER-METSYN-PWY',
    name: "L-methionine biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 35,
    d: 3,
    ratio: '35/3',
    value: 11.666667,
    consonance: 105,
    prime_limit: 7,
    polarity: 0.304,
    polarity_label: 'harmonic',
    cents: 4253.18,
    derivation: "methionine I — sulfhydrylation (35 = 7×5)"
  },
  {
    id: 'PWY0-1061',
    name: "superpathway of L-alanine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Amino Acids',
    n: 14,
    d: 1,
    ratio: '14/1',
    value: 14.0,
    consonance: 14,
    prime_limit: 7,
    polarity: 0.344,
    polarity_label: 'harmonic',
    cents: 4568.83,
    derivation: "alanine — nitrogen shuttle"
  },
  {
    id: 'GLYCOGENSYNTH-PWY',
    name: "glycogen biosynthesis I (from ADP-D-Glucose)",
    category: 'biosynthesis',
    subcategory: 'Carbon Storage',
    n: 1,
    d: 8,
    ratio: '1/8',
    value: 0.125,
    consonance: 8,
    prime_limit: 2,
    polarity: 0.4,
    polarity_label: 'harmonic',
    cents: -3600.0,
    derivation: "glycogen biosynthesis — inert polymeric carbon reserve"
  },
  {
    id: 'PWY-7315',
    name: "dTDP-N-acetylthomosamine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 16,
    d: 245,
    ratio: '16/245',
    value: 0.065306,
    consonance: 3920,
    prime_limit: 7,
    polarity: -0.337,
    polarity_label: 'subharmonic',
    cents: -4723.97,
    derivation: "dTDP-N-acetylthomosamine — common rare identity (7²×5)"
  },
  {
    id: 'PWY-7312',
    name: "dTDP-D-&beta;-fucofuranose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 32,
    d: 245,
    ratio: '32/245',
    value: 0.130612,
    consonance: 7840,
    prime_limit: 7,
    polarity: -0.405,
    polarity_label: 'subharmonic',
    cents: -3523.97,
    derivation: "dTDP-β-D-fucofuranose — moderate identity marker (7²×5)"
  },
  {
    id: 'DTDPRHAMSYN-PWY',
    name: "dTDP-L-rhamnose biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 1,
    d: 7,
    ratio: '1/7',
    value: 0.142857,
    consonance: 7,
    prime_limit: 7,
    polarity: -0.416,
    polarity_label: 'subharmonic',
    cents: -3368.83,
    derivation: "L-rhamnose — external identity marker (1/7)"
  },
  {
    id: 'TEICHOICACID-PWY',
    name: "teichoic acid (poly-glycerol) biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 4,
    d: 21,
    ratio: '4/21',
    value: 0.190476,
    consonance: 84,
    prime_limit: 7,
    polarity: -0.455,
    polarity_label: 'subharmonic',
    cents: -2870.78,
    derivation: "teichoic acid — PG-anchored boundary modulation (3×7)"
  },
  {
    id: 'COLANSYN-PWY',
    name: "colanic acid building blocks biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 32,
    d: 147,
    ratio: '32/147',
    value: 0.217687,
    consonance: 4704,
    prime_limit: 7,
    polarity: -0.476,
    polarity_label: 'subharmonic',
    cents: -2639.61,
    derivation: "colanic acid capsule — adaptive septimal boundary (7²×3)"
  },
  {
    id: 'PEPTIDOGLYCANSYN-PWY',
    name: "peptidoglycan biosynthesis I (meso-diaminopimelate containing)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 8,
    d: 35,
    ratio: '8/35',
    value: 0.228571,
    consonance: 280,
    prime_limit: 7,
    polarity: -0.484,
    polarity_label: 'subharmonic',
    cents: -2555.14,
    derivation: "canonical peptidoglycan"
  },
  {
    id: 'PWY-7316',
    name: "dTDP-N-acetylviosamine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 64,
    d: 245,
    ratio: '64/245',
    value: 0.261224,
    consonance: 15680,
    prime_limit: 7,
    polarity: -0.508,
    polarity_label: 'subharmonic',
    cents: -2323.97,
    derivation: "dTDP-N-acetylviosamine — rare surface identity (7²×5)"
  },
  {
    id: 'PWY-6470',
    name: "peptidoglycan biosynthesis V (&beta;-lactam resistance)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 16,
    d: 49,
    ratio: '16/49',
    value: 0.326531,
    consonance: 784,
    prime_limit: 7,
    polarity: -0.553,
    polarity_label: 'subharmonic',
    cents: -1937.65,
    derivation: "reinforced peptidoglycan"
  },
  {
    id: 'PWY-5265',
    name: "peptidoglycan biosynthesis II (staphylococci)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 16,
    d: 35,
    ratio: '16/35',
    value: 0.457143,
    consonance: 560,
    prime_limit: 7,
    polarity: -0.639,
    polarity_label: 'subharmonic',
    cents: -1355.14,
    derivation: "thickened peptidoglycan"
  },
  {
    id: 'PWY-6471',
    name: "peptidoglycan biosynthesis IV (Enterococcus faecium)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 32,
    d: 63,
    ratio: '32/63',
    value: 0.507937,
    consonance: 2016,
    prime_limit: 7,
    polarity: -0.672,
    polarity_label: 'subharmonic',
    cents: -1172.74,
    derivation: "adaptive peptidoglycan remodeling"
  },
  {
    id: 'PWY-6953',
    name: "dTDP-3-acetamido-3,6-dideoxy-&alpha;-D-galactose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 128,
    d: 245,
    ratio: '128/245',
    value: 0.522449,
    consonance: 31360,
    prime_limit: 7,
    polarity: -0.681,
    polarity_label: 'subharmonic',
    cents: -1123.97,
    derivation: "dTDP-3-acetamido-3,6-dideoxy-galactose — very rare identity (7²×5)"
  },
  {
    id: 'PWY-6385',
    name: "peptidoglycan biosynthesis III (mycobacteria)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 32,
    d: 49,
    ratio: '32/49',
    value: 0.653061,
    consonance: 1568,
    prime_limit: 7,
    polarity: -0.765,
    polarity_label: 'subharmonic',
    cents: -737.65,
    derivation: "extreme peptidoglycan envelope"
  },
  {
    id: 'PWY-6387',
    name: "UDP-N-acetylmuramoyl-pentapeptide biosynthesis I (meso-diaminopimelate containing)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 105,
    d: 128,
    ratio: '105/128',
    value: 0.820312,
    consonance: 13440,
    prime_limit: 7,
    polarity: 0.875,
    polarity_label: 'harmonic',
    cents: -342.91,
    derivation: "UDP-MurNAc variant"
  },
  {
    id: 'PWY-7413',
    name: "dTDP-6-deoxy-&alpha;-D-allose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 256,
    d: 245,
    ratio: '256/245',
    value: 1.044898,
    consonance: 62720,
    prime_limit: 7,
    polarity: -0.969,
    polarity_label: 'subharmonic',
    cents: 76.03,
    derivation: "dTDP-6-deoxy-α-D-allose — extreme / exotic identity (7²×5)"
  },
  {
    id: 'PWY0-1241',
    name: "ADP-L-glycero-&beta;-D-manno-heptose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 147,
    d: 128,
    ratio: '147/128',
    value: 1.148438,
    consonance: 18816,
    prime_limit: 7,
    polarity: 0.909,
    polarity_label: 'harmonic',
    cents: 239.61,
    derivation: "ADP-heptose — LPS inner-core precursor (7²×3)"
  },
  {
    id: 'PWY-6386',
    name: "UDP-N-acetylmuramoyl-pentapeptide biosynthesis II (lysine-containing)",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 105,
    d: 64,
    ratio: '105/64',
    value: 1.640625,
    consonance: 6720,
    prime_limit: 7,
    polarity: 0.737,
    polarity_label: 'harmonic',
    cents: 857.09,
    derivation: "UDP-MurNAc — PG precursor"
  },
  {
    id: 'LPSSYN-PWY',
    name: "superpathway of lipopolysaccharide biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 147,
    d: 64,
    ratio: '147/64',
    value: 2.296875,
    consonance: 9408,
    prime_limit: 7,
    polarity: 0.625,
    polarity_label: 'harmonic',
    cents: 1439.61,
    derivation: "lipopolysaccharide — dominant septimal outer membrane (7²×3)"
  },
  {
    id: 'PWY-5659',
    name: "GDP-mannose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 256,
    d: 105,
    ratio: '256/105',
    value: 2.438095,
    consonance: 26880,
    prime_limit: 7,
    polarity: -0.609,
    polarity_label: 'subharmonic',
    cents: 1542.91,
    derivation: "GDP-mannose — prevalent outer-envelope precursor"
  },
  {
    id: 'UDPNAGSYN-PWY',
    name: "UDP-N-acetyl-D-glucosamine biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 105,
    d: 32,
    ratio: '105/32',
    value: 3.28125,
    consonance: 3360,
    prime_limit: 7,
    polarity: 0.538,
    polarity_label: 'harmonic',
    cents: 2057.09,
    derivation: "UDP-GlcNAc — highest availability"
  },
  {
    id: 'PWY-1269',
    name: "CMP-3-deoxy-D-manno-octulosonate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 245,
    d: 64,
    ratio: '245/64',
    value: 3.828125,
    consonance: 15680,
    prime_limit: 7,
    polarity: 0.508,
    polarity_label: 'harmonic',
    cents: 2323.97,
    derivation: "CMP-KDO — prevalent LPS core anchor"
  },
  {
    id: 'PWY-6478',
    name: "GDP-D-glycero-&alpha;-D-manno-heptose biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 512,
    d: 105,
    ratio: '512/105',
    value: 4.87619,
    consonance: 53760,
    prime_limit: 7,
    polarity: -0.467,
    polarity_label: 'subharmonic',
    cents: 2742.91,
    derivation: "GDP-heptose — specialized outer-core precursor"
  },
  {
    id: 'ECASYN-PWY',
    name: "enterobacterial common antigen biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 147,
    d: 25,
    ratio: '147/25',
    value: 5.88,
    consonance: 3675,
    prime_limit: 7,
    polarity: 0.311,
    polarity_label: 'harmonic',
    cents: 3066.98,
    derivation: "enterobacterial common antigen — group-level surface identity"
  },
  {
    id: 'PWY-6749',
    name: "CMP-legionaminate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 245,
    d: 32,
    ratio: '245/32',
    value: 7.65625,
    consonance: 7840,
    prime_limit: 7,
    polarity: 0.405,
    polarity_label: 'harmonic',
    cents: 3523.97,
    derivation: "CMP-legionaminate — specialized terminal sugar"
  },
  {
    id: 'PWY-6143',
    name: "CMP-pseudaminate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cell Envelope',
    n: 245,
    d: 16,
    ratio: '245/16',
    value: 15.3125,
    consonance: 3920,
    prime_limit: 7,
    polarity: 0.337,
    polarity_label: 'harmonic',
    cents: 4723.97,
    derivation: "CMP-pseudaminate — rare terminal decoration"
  },
  {
    id: 'PWY-6147',
    name: "6-hydroxymethyl-dihydropterin diphosphate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 10,
    ratio: '11/10',
    value: 1.1,
    consonance: 110,
    prime_limit: 11,
    polarity: 0.351,
    polarity_label: 'harmonic',
    cents: 165.0,
    derivation: "Folate precursor — octave echo"
  },
  {
    id: 'P241-PWY',
    name: "coenzyme B biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 55,
    d: 49,
    ratio: '55/49',
    value: 1.122449,
    consonance: 2695,
    prime_limit: 11,
    polarity: 0.053,
    polarity_label: 'neutral',
    cents: 199.98,
    derivation: "Coenzyme B biosynthesis — terminal reductant partner"
  },
  {
    id: 'RIBOSYN2-PWY',
    name: "flavin biosynthesis I (bacteria and plants)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 9,
    ratio: '11/9',
    value: 1.222222,
    consonance: 99,
    prime_limit: 11,
    polarity: 0.087,
    polarity_label: 'neutral',
    cents: 347.41,
    derivation: "Flavin biosynthesis — structural redox cofactor adjacent to NAD (11/9 = 3×3)"
  },
  {
    id: 'PANTOSYN-PWY',
    name: "pantothenate and coenzyme A biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 8,
    ratio: '11/8',
    value: 1.375,
    consonance: 88,
    prime_limit: 11,
    polarity: 0.813,
    polarity_label: 'harmonic',
    cents: 551.32,
    derivation: "CoA biosynthesis I — 11-limit octave 3"
  },
  {
    id: 'PYRIDOXSYN-PWY',
    name: "pyridoxal 5\'-phosphate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 7,
    ratio: '11/7',
    value: 1.571429,
    consonance: 77,
    prime_limit: 11,
    polarity: 0.168,
    polarity_label: 'neutral',
    cents: 782.49,
    derivation: "Vitamin B6 (PLP) biosynthesis — aminotransferase cofactor (11/7)"
  },
  {
    id: 'PWY-5918',
    name: "superpathay of heme biosynthesis from glutamate",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 33,
    d: 20,
    ratio: '33/20',
    value: 1.65,
    consonance: 660,
    prime_limit: 11,
    polarity: 0.541,
    polarity_label: 'harmonic',
    cents: 866.96,
    derivation: "Heme superpathway (from glutamate) — packaged / aggregate"
  },
  {
    id: 'PWY-6895',
    name: "superpathway of thiamin diphosphate biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 6,
    ratio: '11/6',
    value: 1.833333,
    consonance: 66,
    prime_limit: 11,
    polarity: 0.398,
    polarity_label: 'harmonic',
    cents: 1049.36,
    derivation: "Thiamine variant superpathway — octave echo"
  },
  {
    id: 'BIOTIN-BIOSYNTHESIS-PWY',
    name: "biotin biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 21,
    d: 11,
    ratio: '21/11',
    value: 1.909091,
    consonance: 231,
    prime_limit: 11,
    polarity: 0.213,
    polarity_label: 'neutral',
    cents: 1119.46,
    derivation: "Biotin biosynthesis — permissive lipid‑adjacent cofactor"
  },
  {
    id: '1CMET2-PWY',
    name: "N10-formyl-tetrahydrofolate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 5,
    ratio: '11/5',
    value: 2.2,
    consonance: 55,
    prime_limit: 11,
    polarity: 0.239,
    polarity_label: 'neutral',
    cents: 1365.0,
    derivation: "Active folate form — 11/5 anchor"
  },
  {
    id: 'PWY-5507',
    name: "adenosylcobalamin biosynthesis I (early cobalt insertion)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 77,
    d: 32,
    ratio: '77/32',
    value: 2.40625,
    consonance: 2464,
    prime_limit: 11,
    polarity: 0.612,
    polarity_label: 'harmonic',
    cents: 1520.14,
    derivation: "Cobalamin (B12) biosynthesis — de novo (early cobalt insertion)"
  },
  {
    id: 'PWY-5920',
    name: "superpathway of heme biosynthesis from glycine",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 99,
    d: 40,
    ratio: '99/40',
    value: 2.475,
    consonance: 3960,
    prime_limit: 11,
    polarity: 0.547,
    polarity_label: 'harmonic',
    cents: 1568.91,
    derivation: "Heme superpathway (from glycine) — packaged / aggregate"
  },
  {
    id: 'PWY-4242',
    name: "pantothenate and coenzyme A biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 4,
    ratio: '11/4',
    value: 2.75,
    consonance: 44,
    prime_limit: 11,
    polarity: 0.578,
    polarity_label: 'harmonic',
    cents: 1751.32,
    derivation: "CoA biosynthesis III — 11-limit octave 2"
  },
  {
    id: 'PWY-5005',
    name: "biotin biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 35,
    d: 11,
    ratio: '35/11',
    value: 3.181818,
    consonance: 385,
    prime_limit: 11,
    polarity: 0.284,
    polarity_label: 'harmonic',
    cents: 2003.82,
    derivation: "Biotin biosynthesis (alternate) — increased material capacity"
  },
  {
    id: 'HEMESYN2-PWY',
    name: "heme biosynthesis II (anaerobic)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 33,
    d: 10,
    ratio: '33/10',
    value: 3.3,
    consonance: 330,
    prime_limit: 11,
    polarity: 0.396,
    polarity_label: 'harmonic',
    cents: 2066.96,
    derivation: "Heme biosynthesis (anaerobic) — functionalized cofactor"
  },
  {
    id: 'PWY-6823',
    name: "molybdenum cofactor biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 121,
    d: 35,
    ratio: '121/35',
    value: 3.457143,
    consonance: 4235,
    prime_limit: 11,
    polarity: 0.291,
    polarity_label: 'harmonic',
    cents: 2147.5,
    derivation: "Molybdenum cofactor biosynthesis — boundary redox gate"
  },
  {
    id: 'THISYN-PWY',
    name: "superpathway of thiamin diphosphate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 3,
    ratio: '11/3',
    value: 3.666667,
    consonance: 33,
    prime_limit: 11,
    polarity: 0.295,
    polarity_label: 'harmonic',
    cents: 2249.36,
    derivation: "Thiamine main superpathway — 11/3 anchor"
  },
  {
    id: 'PWY-6891',
    name: "thiazole biosynthesis II (Bacillus)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 33,
    d: 8,
    ratio: '33/8',
    value: 4.125,
    consonance: 264,
    prime_limit: 11,
    polarity: 0.495,
    polarity_label: 'harmonic',
    cents: 2453.27,
    derivation: "Thiazole precursor II — building block echo"
  },
  {
    id: 'PWY-6519',
    name: "8-amino-7-oxononanoate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 49,
    d: 11,
    ratio: '49/11',
    value: 4.454545,
    consonance: 539,
    prime_limit: 11,
    polarity: 0.305,
    polarity_label: 'harmonic',
    cents: 2586.33,
    derivation: "Biotin precursor biosynthesis — dense septimal scaffold"
  },
  {
    id: 'PWY-5508',
    name: "adenosylcobalamin biosynthesis from cobyrinate a,c-diamide II",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 77,
    d: 16,
    ratio: '77/16',
    value: 4.8125,
    consonance: 1232,
    prime_limit: 11,
    polarity: 0.469,
    polarity_label: 'harmonic',
    cents: 2720.14,
    derivation: "Cobalamin (B12) biosynthesis — de novo (late cobalt insertion)"
  },
  {
    id: 'HEME-BIOSYNTHESIS-II',
    name: "heme biosynthesis I (aerobic)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 99,
    d: 20,
    ratio: '99/20',
    value: 4.95,
    consonance: 1980,
    prime_limit: 11,
    polarity: 0.42,
    polarity_label: 'harmonic',
    cents: 2768.91,
    derivation: "Heme biosynthesis (aerobic) — functionalized cofactor"
  },
  {
    id: 'COA-PWY',
    name: "coenzyme A biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 2,
    ratio: '11/2',
    value: 5.5,
    consonance: 22,
    prime_limit: 11,
    polarity: 0.448,
    polarity_label: 'harmonic',
    cents: 2951.32,
    derivation: "CoA biosynthesis I — 11-limit octave 1"
  },
  {
    id: 'PWY-5188',
    name: "tetrapyrrole biosynthesis I (from glutamate)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 33,
    d: 5,
    ratio: '33/5',
    value: 6.6,
    consonance: 165,
    prime_limit: 11,
    polarity: 0.312,
    polarity_label: 'harmonic',
    cents: 3266.96,
    derivation: "Tetrapyrrole scaffold (from glutamate) — structural macrocycle"
  },
  {
    id: 'P261-PWY',
    name: "coenzyme M biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 55,
    d: 7,
    ratio: '55/7',
    value: 7.857143,
    consonance: 385,
    prime_limit: 11,
    polarity: 0.311,
    polarity_label: 'harmonic',
    cents: 3568.81,
    derivation: "Coenzyme M biosynthesis — terminal methyl carrier"
  },
  {
    id: 'PWY-6892',
    name: "thiazole biosynthesis I (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 33,
    d: 4,
    ratio: '33/4',
    value: 8.25,
    consonance: 132,
    prime_limit: 11,
    polarity: 0.396,
    polarity_label: 'harmonic',
    cents: 3653.27,
    derivation: "Thiazole precursor I — building block"
  },
  {
    id: 'PWY-5509',
    name: "adenosylcobalamin biosynthesis from cobyrinate a,c-diamide I",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 77,
    d: 8,
    ratio: '77/8',
    value: 9.625,
    consonance: 616,
    prime_limit: 11,
    polarity: 0.38,
    polarity_label: 'harmonic',
    cents: 3920.14,
    derivation: "Cobalamin (B12) biosynthesis — salvage / community route"
  },
  {
    id: 'PWY-5189',
    name: "tetrapyrrole biosynthesis II (from glycine)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 99,
    d: 10,
    ratio: '99/10',
    value: 9.9,
    consonance: 990,
    prime_limit: 11,
    polarity: 0.341,
    polarity_label: 'harmonic',
    cents: 3968.91,
    derivation: "Tetrapyrrole scaffold (from glycine) — recursive structural macrocycle"
  },
  {
    id: 'PYRIDNUCSYN-PWY',
    name: "NAD biosynthesis I (from aspartate)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 11,
    d: 1,
    ratio: '11/1',
    value: 11.0,
    consonance: 11,
    prime_limit: 11,
    polarity: 0.366,
    polarity_label: 'harmonic',
    cents: 4151.32,
    derivation: "NAD biosynthesis I — 11-limit foundation"
  },
  {
    id: 'NADSYN-PWY',
    name: "NAD biosynthesis II (from tryptophan)",
    category: 'biosynthesis',
    subcategory: 'Cofactors/Vitamins',
    n: 121,
    d: 8,
    ratio: '121/8',
    value: 15.125,
    consonance: 968,
    prime_limit: 11,
    polarity: 0.338,
    polarity_label: 'harmonic',
    cents: 4702.64,
    derivation: "NAD biosynthesis II — 11-limit variant"
  },
  {
    id: 'PWY0-881',
    name: "superpathway of fatty acid biosynthesis I (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acid Synthesis',
    n: 35,
    d: 8,
    ratio: '35/8',
    value: 4.375,
    consonance: 280,
    prime_limit: 7,
    polarity: 0.484,
    polarity_label: 'harmonic',
    cents: 2555.14,
    derivation: "FAS superpathway — taxon-specific aggregation"
  },
  {
    id: 'PWY-6284',
    name: "superpathway of unsaturated fatty acids biosynthesis (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acid Synthesis',
    n: 175,
    d: 32,
    ratio: '175/32',
    value: 5.46875,
    consonance: 5600,
    prime_limit: 7,
    polarity: 0.449,
    polarity_label: 'harmonic',
    cents: 2941.45,
    derivation: "FAS unsaturation — constrained adaptation"
  },
  {
    id: 'PWY-6285',
    name: "superpathway of fatty acids biosynthesis (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acid Synthesis',
    n: 105,
    d: 16,
    ratio: '105/16',
    value: 6.5625,
    consonance: 1680,
    prime_limit: 7,
    polarity: 0.424,
    polarity_label: 'harmonic',
    cents: 3257.09,
    derivation: "FAS elongation — full 105-realm engine"
  },
  {
    id: 'FASYN-INITIAL-PWY',
    name: "superpathway of fatty acid biosynthesis initiation (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acid Synthesis',
    n: 35,
    d: 4,
    ratio: '35/4',
    value: 8.75,
    consonance: 140,
    prime_limit: 7,
    polarity: 0.39,
    polarity_label: 'harmonic',
    cents: 3755.14,
    derivation: "FAS initiation — commitment threshold"
  },
  {
    id: 'KDO-NAGLIPASYN-PWY',
    name: "superpathway of (Kdo)2-lipid A biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 35,
    d: 32,
    ratio: '35/32',
    value: 1.09375,
    consonance: 1120,
    prime_limit: 7,
    polarity: 0.939,
    polarity_label: 'harmonic',
    cents: 155.14,
    derivation: "Kdo2-lipid A — immune boundary stress"
  },
  {
    id: 'PWY0-862',
    name: "(5Z)-dodec-5-enoate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 49,
    d: 25,
    ratio: '49/25',
    value: 1.96,
    consonance: 1225,
    prime_limit: 7,
    polarity: 0.218,
    polarity_label: 'neutral',
    cents: 1165.02,
    derivation: "dodecenoate — short-chain flexible lipid"
  },
  {
    id: 'NAGLIPASYN-PWY',
    name: "lipid IVA biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 35,
    d: 16,
    ratio: '35/16',
    value: 2.1875,
    consonance: 560,
    prime_limit: 7,
    polarity: 0.639,
    polarity_label: 'harmonic',
    cents: 1355.14,
    derivation: "lipid IVA — outer membrane scaffold"
  },
  {
    id: 'PWY-5367',
    name: "petroselinate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 63,
    d: 25,
    ratio: '63/25',
    value: 2.52,
    consonance: 1575,
    prime_limit: 7,
    polarity: 0.259,
    polarity_label: 'harmonic',
    cents: 1600.11,
    derivation: "petroselinate — heavy monounsaturated lipid"
  },
  {
    id: 'PWY-5971',
    name: "palmitate biosynthesis II (bacteria and plants)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 147,
    d: 50,
    ratio: '147/50',
    value: 2.94,
    consonance: 7350,
    prime_limit: 7,
    polarity: 0.399,
    polarity_label: 'harmonic',
    cents: 1866.98,
    derivation: "palmitate — saturated membrane anchor"
  },
  {
    id: 'PWY-5989',
    name: "stearate biosynthesis II (bacteria and plants)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 147,
    d: 40,
    ratio: '147/40',
    value: 3.675,
    consonance: 5880,
    prime_limit: 7,
    polarity: 0.482,
    polarity_label: 'harmonic',
    cents: 2253.29,
    derivation: "stearate — saturated rigidity anchor"
  },
  {
    id: 'PWY-6282',
    name: "palmitoleate biosynthesis I (from (5Z)-dodec-5-enoate)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 49,
    d: 9,
    ratio: '49/9',
    value: 5.444444,
    consonance: 441,
    prime_limit: 7,
    polarity: 0.31,
    polarity_label: 'harmonic',
    cents: 2933.74,
    derivation: "palmitoleate — viscous monounsaturated variant"
  },
  {
    id: 'PWY-7664',
    name: "oleate biosynthesis IV (anaerobic)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 49,
    d: 8,
    ratio: '49/8',
    value: 6.125,
    consonance: 392,
    prime_limit: 7,
    polarity: 0.433,
    polarity_label: 'harmonic',
    cents: 3137.65,
    derivation: "oleate IV — light monounsaturated membrane"
  },
  {
    id: 'PWY-5973',
    name: "cis-vaccenate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 49,
    d: 5,
    ratio: '49/5',
    value: 9.8,
    consonance: 245,
    prime_limit: 7,
    polarity: 0.308,
    polarity_label: 'harmonic',
    cents: 3951.34,
    derivation: "cis-vaccenate — flexible membrane curvature"
  },
  {
    id: 'PWY-7663',
    name: "gondoate biosynthesis (anaerobic)",
    category: 'biosynthesis',
    subcategory: 'Fatty Acids / Lipids',
    n: 63,
    d: 5,
    ratio: '63/5',
    value: 12.6,
    consonance: 315,
    prime_limit: 7,
    polarity: 0.302,
    polarity_label: 'harmonic',
    cents: 4386.42,
    derivation: "gondoate — dense long-chain lipid"
  },
  {
    id: 'PWY-5910',
    name: "superpathway of geranylgeranyldiphosphate biosynthesis I (via mevalonate)",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 33,
    d: 7,
    ratio: '33/7',
    value: 4.714286,
    consonance: 231,
    prime_limit: 11,
    polarity: 0.307,
    polarity_label: 'harmonic',
    cents: 2684.45,
    derivation: "GGPP superpathway — boundary-constrained scaffold reserve"
  },
  {
    id: 'PWY-6708',
    name: "ubiquinol-8 biosynthesis (prokaryotic)",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 77,
    d: 15,
    ratio: '77/15',
    value: 5.133333,
    consonance: 1155,
    prime_limit: 11,
    polarity: 0.309,
    polarity_label: 'harmonic',
    cents: 2831.88,
    derivation: "ubiquinol-8 biosynthesis — heavy extended scaffold"
  },
  {
    id: 'PWY-6270',
    name: "isoprene biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 55,
    d: 9,
    ratio: '55/9',
    value: 6.111111,
    consonance: 495,
    prime_limit: 11,
    polarity: 0.312,
    polarity_label: 'harmonic',
    cents: 3133.72,
    derivation: "isoprene biosynthesis — dynamic short-chain pool"
  },
  {
    id: 'POLYISOPRENSYN-PWY',
    name: "polyisoprenoid biosynthesis (E. coli)",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 55,
    d: 8,
    ratio: '55/8',
    value: 6.875,
    consonance: 440,
    prime_limit: 11,
    polarity: 0.418,
    polarity_label: 'harmonic',
    cents: 3337.63,
    derivation: "polyisoprenoid biosynthesis — active scaffold hub"
  },
  {
    id: 'PWY-5838',
    name: "superpathway of menaquinol-8 biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 77,
    d: 10,
    ratio: '77/10',
    value: 7.7,
    consonance: 770,
    prime_limit: 11,
    polarity: 0.355,
    polarity_label: 'harmonic',
    cents: 3533.83,
    derivation: "menaquinol-8 superpathway — adaptive extended scaffold"
  },
  {
    id: 'PWY-5837',
    name: "1,4-dihydroxy-2-naphthoate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 77,
    d: 9,
    ratio: '77/9',
    value: 8.555556,
    consonance: 693,
    prime_limit: 11,
    polarity: 0.31,
    polarity_label: 'harmonic',
    cents: 3716.23,
    derivation: "dihydroxynaphthoate biosynthesis — stable backbone supply"
  },
  {
    id: 'PWY-6859',
    name: "all-trans-farnesol biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Isoprenoids',
    n: 77,
    d: 5,
    ratio: '77/5',
    value: 15.4,
    consonance: 385,
    prime_limit: 11,
    polarity: 0.295,
    polarity_label: 'harmonic',
    cents: 4733.83,
    derivation: "all-trans-farnesol biosynthesis — flexible backbone supply"
  },
  {
    id: 'PWY-5667',
    name: "CDP-diacylglycerol biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Lipids & Membranes',
    n: 45,
    d: 49,
    ratio: '45/49',
    value: 0.918367,
    consonance: 2205,
    prime_limit: 7,
    polarity: -0.04,
    polarity_label: 'neutral',
    cents: -147.43,
    derivation: "CDP-diacylglycerol — boundary capture of fatty material"
  },
  {
    id: 'PHOSLIPSYN-PWY',
    name: "superpathway of phospholipid biosynthesis I (bacteria)",
    category: 'biosynthesis',
    subcategory: 'Lipids & Membranes',
    n: 90,
    d: 49,
    ratio: '90/49',
    value: 1.836735,
    consonance: 4410,
    prime_limit: 7,
    polarity: -0.03,
    polarity_label: 'neutral',
    cents: 1052.57,
    derivation: "phospholipid superpathway — bulk membrane synthesis"
  },
  {
    id: 'PWY4FS-8',
    name: "phosphatidylglycerol biosynthesis II (non-plastidic)",
    category: 'biosynthesis',
    subcategory: 'Lipids & Membranes',
    n: 135,
    d: 49,
    ratio: '135/49',
    value: 2.755102,
    consonance: 6615,
    prime_limit: 7,
    polarity: 0.27,
    polarity_label: 'harmonic',
    cents: 1754.53,
    derivation: "phosphatidylglycerol — active membrane expression"
  },
  {
    id: 'PWY0-162',
    name: "superpathway of pyrimidine ribonucleotides de novo biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 5,
    d: 4,
    ratio: '5/4',
    value: 1.25,
    consonance: 20,
    prime_limit: 5,
    polarity: 0.861,
    polarity_label: 'harmonic',
    cents: 386.31,
    derivation: "RNA pyrimidines — transcriptional expression/color"
  },
  {
    id: 'PWY-7221',
    name: "guanosine ribonucleotides de novo biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 5,
    d: 2,
    ratio: '5/2',
    value: 2.5,
    consonance: 10,
    prime_limit: 5,
    polarity: 0.602,
    polarity_label: 'harmonic',
    cents: 1586.31,
    derivation: "RNA guanosine — execution within continuous time"
  },
  {
    id: 'PWY-7187',
    name: "pyrimidine deoxyribonucleotides de novo biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 15,
    d: 4,
    ratio: '15/4',
    value: 3.75,
    consonance: 60,
    prime_limit: 5,
    polarity: 0.512,
    polarity_label: 'harmonic',
    cents: 2288.27,
    derivation: "DNA pyrimidines — replication completion/fidelity"
  },
  {
    id: 'PWY-7219',
    name: "adenosine ribonucleotides de novo biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 5,
    d: 1,
    ratio: '5/1',
    value: 5.0,
    consonance: 5,
    prime_limit: 5,
    polarity: 0.463,
    polarity_label: 'harmonic',
    cents: 2786.31,
    derivation: "RNA + ATP root — material permission, metabolic time"
  },
  {
    id: 'PWY-7222',
    name: "guanosine deoxyribonucleotides de novo biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 15,
    d: 2,
    ratio: '15/2',
    value: 7.5,
    consonance: 30,
    prime_limit: 5,
    polarity: 0.408,
    polarity_label: 'harmonic',
    cents: 3488.27,
    derivation: "DNA guanosine — replication execution"
  },
  {
    id: 'PWY-6122',
    name: "5-aminoimidazole ribonucleotide biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 10,
    d: 1,
    ratio: '10/1',
    value: 10.0,
    consonance: 10,
    prime_limit: 5,
    polarity: 0.376,
    polarity_label: 'harmonic',
    cents: 3986.31,
    derivation: "Purine precursor — nucleotide pool amplification"
  },
  {
    id: 'PWY-7220',
    name: "adenosine deoxyribonucleotides de novo biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Nucleotides',
    n: 15,
    d: 1,
    ratio: '15/1',
    value: 15.0,
    consonance: 15,
    prime_limit: 5,
    polarity: 0.339,
    polarity_label: 'harmonic',
    cents: 4688.27,
    derivation: "DNA adenosine — commitment to replication"
  },
  {
    id: 'PWY-6351',
    name: "D-myo-inositol (1,4,5)-trisphosphate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 15,
    d: 8,
    ratio: '15/8',
    value: 1.875,
    consonance: 120,
    prime_limit: 5,
    polarity: 0.688,
    polarity_label: 'harmonic',
    cents: 1088.27,
    derivation: "inositol-1,4,5-P3 — signaling molecule (3×5/2³)"
  },
  {
    id: 'PWY-6148',
    name: "tetrahydromethanopterin biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 143,
    d: 32,
    ratio: '143/32',
    value: 4.46875,
    consonance: 4576,
    prime_limit: 13,
    polarity: 0.481,
    polarity_label: 'harmonic',
    cents: 2591.85,
    derivation: "tetrahydromethanopterin — methanogen C1 carrier (11×13/2⁵)"
  },
  {
    id: 'ARO-PWY',
    name: "chorismate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 13,
    d: 2,
    ratio: '13/2',
    value: 6.5,
    consonance: 26,
    prime_limit: 13,
    polarity: 0.425,
    polarity_label: 'harmonic',
    cents: 3240.53,
    derivation: "chorismate — alternative implementation of the aromatic decision point (Prime 13, secondary register)"
  },
  {
    id: 'PWY-6349',
    name: "CDP-archaeol biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 143,
    d: 16,
    ratio: '143/16',
    value: 8.9375,
    consonance: 2288,
    prime_limit: 13,
    polarity: 0.388,
    polarity_label: 'harmonic',
    cents: 3791.85,
    derivation: "CDP-archaeol — archaeal membrane precursor (11×13/2⁴)"
  },
  {
    id: 'PWY-7374',
    name: "1,4-dihydroxy-6-naphthoate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 77,
    d: 6,
    ratio: '77/6',
    value: 12.833333,
    consonance: 462,
    prime_limit: 11,
    polarity: 0.326,
    polarity_label: 'harmonic',
    cents: 4418.19,
    derivation: "naphthoate — menaquinone precursor (7×11/2×3)"
  },
  {
    id: 'PWY-6163',
    name: "chorismate biosynthesis from 3-dehydroquinate",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 13,
    d: 1,
    ratio: '13/1',
    value: 13.0,
    consonance: 13,
    prime_limit: 13,
    polarity: 0.351,
    polarity_label: 'harmonic',
    cents: 4440.53,
    derivation: "chorismate — dominant irreversible decision point into aromatic biosynthetic futures (Prime 13)"
  },
  {
    id: 'PWY-5198',
    name: "factor 420 biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 55,
    d: 4,
    ratio: '55/4',
    value: 13.75,
    consonance: 220,
    prime_limit: 11,
    polarity: 0.346,
    polarity_label: 'harmonic',
    cents: 4537.63,
    derivation: "factor F420 — methanogen deazaflavin cofactor (5×11/2²)"
  },
  {
    id: 'PWY-7377',
    name: "cob(II)yrinate a,c-diamide biosynthesis I (early cobalt insertion)",
    category: 'biosynthesis',
    subcategory: 'Other',
    n: 231,
    d: 16,
    ratio: '231/16',
    value: 14.4375,
    consonance: 3696,
    prime_limit: 11,
    polarity: 0.342,
    polarity_label: 'harmonic',
    cents: 4622.1,
    derivation: "cob(II)yrinate — B12 precursor (3×7×11/2⁴)"
  },
  {
    id: 'PWY-6834',
    name: "spermidine biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 21,
    ratio: '25/21',
    value: 1.190476,
    consonance: 525,
    prime_limit: 7,
    polarity: 0.077,
    polarity_label: 'neutral',
    cents: 301.85,
    derivation: "spermidine biosynthesis III — rare / specialized pool"
  },
  {
    id: 'PWY-6565',
    name: "superpathway of polyamine biosynthesis III",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 16,
    ratio: '25/16',
    value: 1.5625,
    consonance: 400,
    prime_limit: 5,
    polarity: 0.756,
    polarity_label: 'harmonic',
    cents: 772.63,
    derivation: "polyamine superpathway III — low-abundance extension"
  },
  {
    id: 'PWY-6562',
    name: "norspermidine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 12,
    ratio: '25/12',
    value: 2.083333,
    consonance: 300,
    prime_limit: 5,
    polarity: 0.514,
    polarity_label: 'harmonic',
    cents: 1270.67,
    derivation: "norspermidine biosynthesis — geometric modulation"
  },
  {
    id: 'POLYAMINSYN3-PWY',
    name: "superpathway of polyamine biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 8,
    ratio: '25/8',
    value: 3.125,
    consonance: 200,
    prime_limit: 5,
    polarity: 0.549,
    polarity_label: 'harmonic',
    cents: 1972.63,
    derivation: "polyamine superpathway II — extended buffering"
  },
  {
    id: 'POLYAMSYN-PWY',
    name: "superpathway of polyamine biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 4,
    ratio: '25/4',
    value: 6.25,
    consonance: 100,
    prime_limit: 5,
    polarity: 0.431,
    polarity_label: 'harmonic',
    cents: 3172.63,
    derivation: "polyamine superpathway I — expanded buffering"
  },
  {
    id: 'PWY-6305',
    name: "putrescine biosynthesis IV",
    category: 'biosynthesis',
    subcategory: 'Polyamines',
    n: 25,
    d: 2,
    ratio: '25/2',
    value: 12.5,
    consonance: 50,
    prime_limit: 5,
    polarity: 0.354,
    polarity_label: 'harmonic',
    cents: 4372.63,
    derivation: "putrescine biosynthesis — baseline polyamine pool"
  },
  {
    id: 'PWY-7090',
    name: "UDP-2,3-diacetamido-2,3-dideoxy-α-D-mannuronate biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 245,
    d: 256,
    ratio: '245/256',
    value: 0.957031,
    consonance: 62720,
    prime_limit: 7,
    polarity: 0.969,
    polarity_label: 'harmonic',
    cents: -76.03,
    derivation: "UDP-ManNAc — rare surface identity (7²×5/2⁸)"
  },
  {
    id: 'P125-PWY',
    name: "superpathway of (R,R)-butanediol biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 27,
    d: 20,
    ratio: '27/20',
    value: 1.35,
    consonance: 540,
    prime_limit: 5,
    polarity: 0.565,
    polarity_label: 'harmonic',
    cents: 519.55,
    derivation: "butanediol — fermentation product (3³/4×5)"
  },
  {
    id: 'PWY-7255',
    name: "ergothioneine biosynthesis I (bacteria)",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 55,
    d: 32,
    ratio: '55/32',
    value: 1.71875,
    consonance: 1760,
    prime_limit: 11,
    polarity: 0.719,
    polarity_label: 'harmonic',
    cents: 937.63,
    derivation: "ergothioneine — histidine-derived antioxidant (5×11/2⁵)"
  },
  {
    id: 'PWY-5656',
    name: "mannosylglycerate biosynthesis I",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 9,
    d: 5,
    ratio: '9/5',
    value: 1.8,
    consonance: 45,
    prime_limit: 5,
    polarity: 0.201,
    polarity_label: 'neutral',
    cents: 1017.6,
    derivation: "mannosylglycerate — osmolyte, stress protection (3²/5)"
  },
  {
    id: 'PWY-5514',
    name: "UDP-N-acetyl-D-galactosamine biosynthesis II",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 245,
    d: 128,
    ratio: '245/128',
    value: 1.914062,
    consonance: 31360,
    prime_limit: 7,
    polarity: 0.681,
    polarity_label: 'harmonic',
    cents: 1123.97,
    derivation: "UDP-GalNAc — surface sugar (7²×5/2⁷)"
  },
  {
    id: 'PWY-5173',
    name: "superpathway of acetyl-CoA biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 33,
    d: 16,
    ratio: '33/16',
    value: 2.0625,
    consonance: 528,
    prime_limit: 11,
    polarity: 0.657,
    polarity_label: 'harmonic',
    cents: 1253.27,
    derivation: "acetyl-CoA — universal 2C donor (3×11/2⁴)"
  },
  {
    id: 'CITRULBIO-PWY',
    name: "L-citrulline biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 27,
    d: 10,
    ratio: '27/10',
    value: 2.7,
    consonance: 270,
    prime_limit: 5,
    polarity: 0.401,
    polarity_label: 'harmonic',
    cents: 1719.55,
    derivation: "citrulline — urea cycle shuttle (3³/2×5)"
  },
  {
    id: 'PWY-5695',
    name: "urate biosynthesis/inosine 5'-phosphate degradation",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 25,
    d: 9,
    ratio: '25/9',
    value: 2.777778,
    consonance: 225,
    prime_limit: 5,
    polarity: 0.271,
    polarity_label: 'harmonic',
    cents: 1768.72,
    derivation: "urate — purine endpoint, nitrogen excretion (5²/3²)"
  },
  {
    id: 'PWY1G-0',
    name: "mycothiol biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 55,
    d: 16,
    ratio: '55/16',
    value: 3.4375,
    consonance: 880,
    prime_limit: 11,
    polarity: 0.529,
    polarity_label: 'harmonic',
    cents: 2137.63,
    derivation: "mycothiol — antioxidant, mycobacterial glutathione (5×11/2⁴)"
  },
  {
    id: 'GLUTORN-PWY',
    name: "L-ornithine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 27,
    d: 5,
    ratio: '27/5',
    value: 5.4,
    consonance: 135,
    prime_limit: 5,
    polarity: 0.31,
    polarity_label: 'harmonic',
    cents: 2919.55,
    derivation: "ornithine — nitrogen pool for arginine/polyamines (3³/5)"
  },
  {
    id: 'URSIN-PWY',
    name: "ureide biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 45,
    d: 8,
    ratio: '45/8',
    value: 5.625,
    consonance: 360,
    prime_limit: 5,
    polarity: 0.445,
    polarity_label: 'harmonic',
    cents: 2990.22,
    derivation: "ureide — nitrogen transport compound (9×5/2³)"
  },
  {
    id: 'AEROBACTINSYN-PWY',
    name: "aerobactin biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 91,
    d: 16,
    ratio: '91/16',
    value: 5.6875,
    consonance: 1456,
    prime_limit: 13,
    polarity: 0.444,
    polarity_label: 'harmonic',
    cents: 3009.35,
    derivation: "aerobactin — hydroxamate siderophore variant (7×13/2⁴)"
  },
  {
    id: 'ENTBACSYN-PWY',
    name: "enterobactin biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Specialized',
    n: 91,
    d: 8,
    ratio: '91/8',
    value: 11.375,
    consonance: 728,
    prime_limit: 13,
    polarity: 0.363,
    polarity_label: 'harmonic',
    cents: 4209.35,
    derivation: "enterobactin — primary siderophore, iron scavenger (7×13/2³)"
  },
  {
    id: 'PPGPPMET-PWY',
    name: "ppGpp biosynthesis",
    category: 'biosynthesis',
    subcategory: 'Stress / Decision',
    n: 13,
    d: 5,
    ratio: '13/5',
    value: 2.6,
    consonance: 65,
    prime_limit: 13,
    polarity: 0.263,
    polarity_label: 'harmonic',
    cents: 1654.21,
    derivation: "ppGpp biosynthesis — guanosine-based global decision signal"
  },
  {
    id: 'PWY-7286',
    name: "7-(3-amino-3-carboxypropyl)-wyosine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'tRNA Modifications',
    n: 75,
    d: 49,
    ratio: '75/49',
    value: 1.530612,
    consonance: 3675,
    prime_limit: 7,
    polarity: 0.16,
    polarity_label: 'neutral',
    cents: 736.93,
    derivation: "wyosine derivative — identity-anchored tRNA modification"
  },
  {
    id: 'PWY-6703',
    name: "preQ0 biosynthesis",
    category: 'biosynthesis',
    subcategory: 'tRNA Modifications',
    n: 75,
    d: 32,
    ratio: '75/32',
    value: 2.34375,
    consonance: 2400,
    prime_limit: 5,
    polarity: 0.619,
    polarity_label: 'harmonic',
    cents: 1474.58,
    derivation: "preQ0 — metabolic precursor to queuosine"
  },
  {
    id: 'PWY-6700',
    name: "queuosine biosynthesis",
    category: 'biosynthesis',
    subcategory: 'tRNA Modifications',
    n: 75,
    d: 16,
    ratio: '75/16',
    value: 4.6875,
    consonance: 1200,
    prime_limit: 5,
    polarity: 0.473,
    polarity_label: 'harmonic',
    cents: 2674.58,
    derivation: "queuosine — tRNA wobble-base modification"
  },
];

// Export for use in visualization
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { COMPOSED_RATIOS };
}
